# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3bc8fa74bf49a45c2d6d3fc02b8e58699b884f023045e30c55675a33ffde658d48411b6b86321b70e931597eb7356b58c50cda9845b5d923de41f10a204afc2

test:
  secret_key_base: 3f4139b6a73fec8d66deb70d09eb47fee5a9dec705a8f645a85d358910417b09406e6f55f1f50e993553d631dd3297a00807161ec837ebb56fdb83c3ef1a4da8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
